### ISSUE TITLE
SyntaxError when importing on Python 3.4

### ISSUE THREAD

**Issue by mratmartinez** [fmakdemir/colored-logger#4]
When I try to import from Python 3.4 (which is the last stable version on Gentoo) it raises a SyntaxError.

```
Python 3.4.5 (default, Jan  6 2018, 08:36:00)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coloredlogger import ColoredLogger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrat/.local/lib64/python3.4/site-packages/coloredlogger.py", line 89
    args = [*args, Style.RESET_ALL]
             ^
SyntaxError: can use starred expression only as assignment target
>>> import coloredlogger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrat/.local/lib64/python3.4/site-packages/coloredlogger.py", line 89
    args = [*args, Style.RESET_ALL]
             ^
SyntaxError: can use starred expression only as assignment target
```

Was installed with the pip version.

**Comment by fmakdemir** [comment]
Thanks @mratmartinez I will check it asap

**Comment by fmakdemir** [comment]
@mratmartinez it should be fixed now you can update the package and thanks for letting me know!
